#!/bin/bash
#    

STEP=$BLOCK_INSTANCE

case $BLOCK_BUTTON in
  3) amixer -q set Master toggle ;;  # right click, mute/unmute
  4) amixer -q set Master ${STEP}+ unmute ;; # scroll up, increase
  5) amixer -q set Master ${STEP}- unmute ;; # scroll down, decrease
esac

VALUE=$(pamixer --get-volume)
MUTE=$(pamixer --get-mute)
IMAGE=""

# mute
if [[ $MUTE = "true" || $VALUE = "0%" ]]; then
  IMAGE=""
  COLOR1="#7D6F67"
  COLOR2="#7D6F67"
# not mute
else
  COLOR1="#FFD29E"
  COLOR2="#EBD1B7"
fi

echo "<span color='$COLOR1'>$IMAGE</span> <span color='$COLOR2'>$VALUE%</span>"
